// data.js

export const stores = [
  {
    id: 1,
    name: "Harmony Music Store",
    description: "Premium guitars, keyboards, drums, and music accessories.",
    address: "221B MG Road, Bengaluru, Karnataka 560001",
    phone: "+91 9876543210",
    email: "contact@harmonymusic.com",
    website: "https://harmonymusic.example.com",
    imageUrl: "https://picsum.photos/seed/harmony/600/600",
  },
  {
    id: 2,
    name: "Urban Electronics",
    description: "Latest smartphones, laptops, gaming accessories, and gadgets.",
    address: "45 Park Street, Kolkata, West Bengal 700016",
    phone: "+91 9123456789",
    email: "support@urbanelectronics.com",
    website: "https://urbanelectronics.example.com",
    imageUrl: "https://picsum.photos/seed/electronics/600/600",
  },
  {
    id: 3,
    name: "Fresh Basket",
    description: "Organic groceries, vegetables, fruits, and dairy products.",
    address: "12 Green Avenue, Pune, Maharashtra 411001",
    phone: "+91 9988776655",
    email: "hello@freshbasket.com",
    website: "https://freshbasket.example.com",
    imageUrl: "https://picsum.photos/seed/grocery/600/600",
  },
  {
    id: 4,
    name: "Elite Fashion Hub",
    description: "Modern fashion, footwear, handbags, and accessories.",
    address: "88 Brigade Road, Bengaluru, Karnataka 560025",
    phone: "+91 9012345678",
    email: "sales@elitefashionhub.com",
    website: "https://elitefashionhub.example.com",
    imageUrl: "https://picsum.photos/seed/fashion/600/600",
  },
  {
    id: 5,
    name: "TechNest Computers",
    description: "Gaming PCs, laptops, custom builds, and repair services.",
    address: "17 Nehru Place, New Delhi 110019",
    phone: "+91 9876123456",
    email: "info@technestcomputers.com",
    website: "https://technestcomputers.example.com",
    imageUrl: "https://picsum.photos/seed/computers/600/600",
  },
  {
    id: 6,
    name: "Book Haven",
    description: "Books, stationery, journals, and office supplies.",
    address: "10 FC Road, Pune, Maharashtra 411004",
    phone: "+91 9090909090",
    email: "contact@bookhaven.com",
    website: "https://bookhaven.example.com",
    imageUrl: "https://picsum.photos/seed/books/600/600",
  },
  {
    id: 7,
    name: "Fitness Factory",
    description: "Gym equipment, supplements, and fitness accessories.",
    address: "5 Anna Salai, Chennai, Tamil Nadu 600002",
    phone: "+91 9345678901",
    email: "support@fitnessfactory.com",
    website: "https://fitnessfactory.example.com",
    imageUrl: "https://picsum.photos/seed/fitness/600/600",
  },
  {
    id: 8,
    name: "Pet Paradise",
    description: "Pet food, grooming products, toys, and accessories.",
    address: "91 Marine Drive, Mumbai, Maharashtra 400020",
    phone: "+91 9234567890",
    email: "care@petparadise.com",
    website: "https://petparadise.example.com",
    imageUrl: "https://picsum.photos/seed/pets/600/600",
  },
  {
    id: 9,
    name: "Green Garden",
    description: "Plants, pots, fertilizers, and gardening tools.",
    address: "56 Civil Lines, Jaipur, Rajasthan 302006",
    phone: "+91 9789012345",
    email: "hello@greengarden.com",
    website: "https://greengarden.example.com",
    imageUrl: "https://picsum.photos/seed/garden/600/600",
  },
  {
    id: 10,
    name: "Home Essentials",
    description: "Kitchenware, furniture, lighting, and home decor.",
    address: "27 Residency Road, Hyderabad, Telangana 500001",
    phone: "+91 9011223344",
    email: "sales@homeessentials.com",
    website: "https://homeessentials.example.com",
    imageUrl: "https://picsum.photos/seed/home/600/600",
  },
  {
    id: 11,
    name: "Sports Arena",
    description: "Cricket, football, badminton, and outdoor sports gear.",
    address: "14 Sector 18, Noida, Uttar Pradesh 201301",
    phone: "+91 9887766554",
    email: "info@sportsarena.com",
    website: "https://sportsarena.example.com",
    imageUrl: "https://picsum.photos/seed/sports/600/600",
  },
  {
    id: 12,
    name: "Beauty Bliss",
    description: "Cosmetics, skincare, fragrances, and beauty essentials.",
    address: "32 Linking Road, Mumbai, Maharashtra 400050",
    phone: "+91 9765432109",
    email: "contact@beautybliss.com",
    website: "https://beautybliss.example.com",
    imageUrl: "https://picsum.photos/seed/beauty/600/600",
  },
  {
    id: 13,
    name: "Toy World",
    description: "Educational toys, board games, and kids' gifts.",
    address: "77 Banjara Hills, Hyderabad, Telangana 500034",
    phone: "+91 9654321098",
    email: "hello@toyworld.com",
    website: "https://toyworld.example.com",
    imageUrl: "https://picsum.photos/seed/toys/600/600",
  },
  {
    id: 14,
    name: "Coffee Corner",
    description: "Fresh coffee beans, brewing equipment, and cafe supplies.",
    address: "18 Church Street, Bengaluru, Karnataka 560001",
    phone: "+91 9543210987",
    email: "brew@coffeecorner.com",
    website: "https://coffeecorner.example.com",
    imageUrl: "https://picsum.photos/seed/coffee/600/600",
  },
  {
    id: 15,
    name: "Cycle Hub",
    description: "Mountain bikes, road bikes, helmets, and cycling gear.",
    address: "64 Ring Road, Ahmedabad, Gujarat 380015",
    phone: "+91 9432109876",
    email: "ride@cyclehub.com",
    website: "https://cyclehub.example.com",
    imageUrl: "https://picsum.photos/seed/cycle/600/600",
  },
];